export const DEFAULT_BOOK_CATEGORIES = [
  'Dünya Klasikleri',
  'Türk Klasikleri',
  'Fantastik & Roman',
  'Bilim Kurgu & Distopya',
  'Felsefe & Düşünce',
  'Felsefe & Roman',
  'Psikoloji & Dram',
  'Psikoloji & Roman',
  'Tarih & Tarihi Kurgu',
  'Polisiye & Suç',
  'Korku & Gerilim',
  'Öykü & Hikaye',
  'Deneme & Eleştiri',
  'Biyografi & Otobiyografi',
  'Mizah & Hiciv',
  'Politik & Sosyolojik Roman',
  'Mitoloji & Destan',
  'Aşk & Romantik Roman',
  'Macera & Aksiyon',
  'Şiir & Antoloji',
  'Tiyatro & Oyun',
  'Tasavvuf & Doğu Felsefesi',
  'Gotik & Karanlık Kurgu',
  'Çocuk & Gençlik Edebiyatı',
  'Roman',
];
