export const DEFAULT_BOOK_CATEGORIES = [
  'Dünya Klasikleri',
  'Felsefe & Düşünce',
  'Felsefe & Stoa',
  'Felsefe & Politika',
  'Deneme & Felsefe',
  'Roman & Klasik',
  'Roman & Felsefe',
  'Distopya & Roman',
  'Fantastik & Roman',
  'Psikoloji & Felsefe',
  'Şiir & Edebiyat',
  'Sanat & Estetik',
  'Tarih & Biyografi',
  'Korku & Gerilim',
  'Bilim Kurgu',
  'Biyografi & Otobiyografi',
  'Mitoloji & Destan',
];
